
package br.com.fiap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlunoWeb2Service", targetNamespace = "http://ws.exemplo.fiap.com/", wsdlLocation = "http://l2704micro02:8080/Aula2/AlunoWeb2Service?wsdl")
public class AlunoWeb2Service
    extends Service
{

    private final static URL ALUNOWEB2SERVICE_WSDL_LOCATION;
    private final static WebServiceException ALUNOWEB2SERVICE_EXCEPTION;
    private final static QName ALUNOWEB2SERVICE_QNAME = new QName("http://ws.exemplo.fiap.com/", "AlunoWeb2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://l2704micro02:8080/Aula2/AlunoWeb2Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALUNOWEB2SERVICE_WSDL_LOCATION = url;
        ALUNOWEB2SERVICE_EXCEPTION = e;
    }

    public AlunoWeb2Service() {
        super(__getWsdlLocation(), ALUNOWEB2SERVICE_QNAME);
    }

    public AlunoWeb2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALUNOWEB2SERVICE_QNAME, features);
    }

    public AlunoWeb2Service(URL wsdlLocation) {
        super(wsdlLocation, ALUNOWEB2SERVICE_QNAME);
    }

    public AlunoWeb2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALUNOWEB2SERVICE_QNAME, features);
    }

    public AlunoWeb2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlunoWeb2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlunoWeb2
     */
    @WebEndpoint(name = "AlunoWeb2Port")
    public AlunoWeb2 getAlunoWeb2Port() {
        return super.getPort(new QName("http://ws.exemplo.fiap.com/", "AlunoWeb2Port"), AlunoWeb2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlunoWeb2
     */
    @WebEndpoint(name = "AlunoWeb2Port")
    public AlunoWeb2 getAlunoWeb2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.exemplo.fiap.com/", "AlunoWeb2Port"), AlunoWeb2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALUNOWEB2SERVICE_EXCEPTION!= null) {
            throw ALUNOWEB2SERVICE_EXCEPTION;
        }
        return ALUNOWEB2SERVICE_WSDL_LOCATION;
    }

}
