
package br.com.fiap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlunoWeb", targetNamespace = "http://ws.exemplo.fiap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlunoWeb {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ola", targetNamespace = "http://ws.exemplo.fiap.com/", className = "br.com.fiap.client.Ola")
    @ResponseWrapper(localName = "olaResponse", targetNamespace = "http://ws.exemplo.fiap.com/", className = "br.com.fiap.client.OlaResponse")
    @Action(input = "http://ws.exemplo.fiap.com/AlunoWeb/olaRequest", output = "http://ws.exemplo.fiap.com/AlunoWeb/olaResponse")
    public String ola(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.client.Aluno>
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://ws.exemplo.fiap.com/", className = "br.com.fiap.client.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://ws.exemplo.fiap.com/", className = "br.com.fiap.client.ListarResponse")
    @Action(input = "http://ws.exemplo.fiap.com/AlunoWeb/listarRequest", output = "http://ws.exemplo.fiap.com/AlunoWeb/listarResponse", fault = {
        @FaultAction(className = AccessDeniedException_Exception.class, value = "http://ws.exemplo.fiap.com/AlunoWeb/listar/Fault/AccessDeniedException")
    })
    public List<Aluno> listar()
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "novo", targetNamespace = "http://ws.exemplo.fiap.com/", className = "br.com.fiap.client.Novo")
    @ResponseWrapper(localName = "novoResponse", targetNamespace = "http://ws.exemplo.fiap.com/", className = "br.com.fiap.client.NovoResponse")
    @Action(input = "http://ws.exemplo.fiap.com/AlunoWeb/novoRequest", output = "http://ws.exemplo.fiap.com/AlunoWeb/novoResponse")
    public String novo(
        @WebParam(name = "arg0", targetNamespace = "")
        Aluno arg0);

}
